name: Build

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dist-all-packages:
    runs-on: ubuntu-latest

    # Add env vars for tests
    env:
      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
      TEST_2_MNEMONIC: ${{ secrets.TEST_2_MNEMONIC }}
      TEST_NODE_MNEMONIC: ${{ secrets.TEST_NODE_MNEMONIC }}

    steps:
      # Get the code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Setup any services required for tests here
      - name: Download IOTA CLI
        run: |
          wget https://github.com/iotaledger/iota/releases/download/v0.12.0-rc/iota-v0.12.0-rc-linux-x86_64.tgz -O iota-cli.tgz
          tar xzf iota-cli.tgz
          chmod +x iota
          sudo mv iota /usr/local/bin/iota
          iota --version
      # End setup for tests
      # Run Lint and Dist
      - name: Run Lint and Dist
        run: |
          npm run lint
          npm run dist
