name: Publish Next All Packages

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    env:
      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
      TEST_NODE_MNEMONIC: ${{ secrets.TEST_NODE_MNEMONIC }}

    if: github.ref != 'refs/heads/main'

    strategy:
      max-parallel: 1
      matrix:
        package:
          [
            'packages/verifiable-storage-models',
            'packages/verifiable-storage-connector-entity-storage',
            'packages/verifiable-storage-connector-iota',
            'packages/verifiable-storage-connector-iota-stardust',
            'packages/verifiable-storage-service',
            'packages/verifiable-storage-rest-client'
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: next

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Remove Mono-Repo Node Modules
        run: |
          rm package.json
          rm package-lock.json

      - name: Check package version contains -next
        run: |
          cd ${{ matrix.package }}
          PACKAGE_VERSION=$(cat package.json | jq '.version' | tr -d '"')
          echo Package Version $PACKAGE_VERSION
          if [[ $PACKAGE_VERSION != *"-next"* ]]; then
            echo "Error: package version does not contain -next"
            exit 1
          fi

      - name: Download IOTA CLI
        run: |
          wget https://github.com/iotaledger/iota/releases/download/v0.9.2-rc/iota-v0.9.2-rc-linux-x86_64.tgz -O iota-cli.tgz
          tar xzf iota-cli.tgz
          chmod +x iota
          sudo mv iota /usr/local/bin/iota
          iota --version

      - name: Run Dist
        run: |
          cd ${{ matrix.package }}
          npm install
          npm run dist

      - name: Cleanup package properties
        run: |
          cd ${{ matrix.package }}
          npm pkg delete scripts
          npm pkg delete devDependencies

      - name: Publish
        run: |
          cd ${{ matrix.package }}
          npm publish --provenance --access public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
